/* @pjs pauseOnBlur="true";
        font="fonts/acmesa.ttf";
        preload="graphics/mute.gif,
                 graphics/unmute.gif,
                 
                 graphics/decals/100.gif,
                 graphics/decals/200.gif,
                 graphics/decals/300.gif,
                 graphics/decals/400.gif,
                 graphics/decals/500.gif,
                 graphics/decals/1000.gif,

                 graphics/backgrounds/ground-filler.gif,
                 graphics/backgrounds/ground-slant.gif,
                 graphics/backgrounds/ground-top.gif,

                 graphics/backgrounds/ground-corner-left.gif,
                 graphics/backgrounds/ground-corner-right.gif,
                 graphics/backgrounds/ground-side-left.gif,
                 graphics/backgrounds/ground-side-right.gif,

                 graphics/backgrounds/sky.gif,
                 graphics/backgrounds/bush-01.gif,
                 graphics/backgrounds/bush-02.gif,
                 graphics/backgrounds/bush-03.gif,
                 graphics/backgrounds/bush-04.gif,
                 graphics/backgrounds/bush-05.gif,

                 graphics/assorted/Dragon-coin.gif,
                 graphics/assorted/Regular-coin.gif,
                 graphics/assorted/Mushroom.gif,
                 graphics/assorted/Block.gif,
                 graphics/assorted/Coin-block.gif,
                 graphics/assorted/Coin-block-exhausted.gif,
                 graphics/assorted/Passthrough-block.gif,
                 graphics/assorted/Goal-front.gif,
                 graphics/assorted/Goal-back.gif,
                 graphics/assorted/Goal-slider.gif,
                 graphics/assorted/Pipe-head.gif,
                 graphics/assorted/Pipe-body.gif,

                 graphics/enemies/Dead-koopa.gif,
                 graphics/enemies/Naked-koopa-walking.gif,
                 graphics/enemies/Red-koopa-walking.gif,
                 graphics/enemies/Red-koopa-standing.gif,
                 graphics/enemies/Red-koopa-flying.gif,
                 graphics/enemies/Banzai-bill.gif,
                 graphics/enemies/Boo-chasing.gif,
                 graphics/enemies/Boo-waiting.gif,
                 graphics/enemies/Coin-boo-transition.gif,

                 graphics/mario/small/Crouching-mario.gif,
                 graphics/mario/small/Dead-mario.gif,
                 graphics/mario/small/Jumping-mario.gif,
                 graphics/mario/small/Looking-mario.gif,
                 graphics/mario/small/Running-mario.gif,
                 graphics/mario/small/Spinning-mario.gif,
                 graphics/mario/small/Standing-mario.gif,

                 graphics/mario/big/Crouching-mario.gif,
                 graphics/mario/big/Dead-mario.gif,
                 graphics/mario/big/Jumping-mario.gif,
                 graphics/mario/big/Looking-mario.gif,
                 graphics/mario/big/Running-mario.gif,
                 graphics/mario/big/Spinning-mario.gif,
                 graphics/mario/big/Standing-mario.gif"; */
